// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCYA8d-dnXSLdBGpRy2FS9dO-lQ-w_nU',
    appId: '1:146260254407:web:885eb422aeeb962ed328e2',
    messagingSenderId: '146260254407',
    projectId: 'videochat-5a833',
    authDomain: 'videochat-5a833.firebaseapp.com',
    databaseURL: 'https://videochat-5a833-default-rtdb.firebaseio.com',
    storageBucket: 'videochat-5a833.appspot.com',
    measurementId: 'G-509GCVF4HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArTJn_Mbndw-QwGUDii4EpEmZ8OKIKPaY',
    appId: '1:146260254407:android:6d82c91e94e34c33d328e2',
    messagingSenderId: '146260254407',
    projectId: 'videochat-5a833',
    databaseURL: 'https://videochat-5a833-default-rtdb.firebaseio.com',
    storageBucket: 'videochat-5a833.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55Rah1_HbOr2-evQKx1TKoOOPhsLQCjk',
    appId: '1:146260254407:ios:9fa38b9818068d28d328e2',
    messagingSenderId: '146260254407',
    projectId: 'videochat-5a833',
    databaseURL: 'https://videochat-5a833-default-rtdb.firebaseio.com',
    storageBucket: 'videochat-5a833.appspot.com',
    androidClientId: '146260254407-dl7s0e48fs7vs0k5av3ibalaih53g10r.apps.googleusercontent.com',
    iosClientId: '146260254407-ldh7ac4kchij1c75u6o5jkfubirvvqun.apps.googleusercontent.com',
    iosBundleId: 'com.future.watsapp',
  );
}
